### ISSUE TITLE
Startup Problems 3 (NONE)

### ISSUE THREAD

**Issue by Stefdv** [apguerard/HandleView-DevPreview#3]
That's it , follow startup problems1 and 2 and your demoapp is up and running. Thank yo Alain 👍

**Comment by Stefdv** [comment]
Startup problems are all fixed so closing this issue as well.
Note to users : DO read the documentation 😉

**Comment by apguerard** [comment]
Thanks Stef.
What do you think about it at first sight ? Too complicated ?

I will try to finish the documentation for navigation and how to build component soon, that's the heart of the framework..

**Comment by Stefdv** [comment]
No, not too complicated...overwhelming maybe. I really really like your approach especially your component structure 👍 
One question on forhand... is sending parameters allready implemented ? because i tried to read out args(0) in executeJSFromButton but i stays empty ? ( i did set a parameter in my html )
ps i started a gitter room for handleview (maybe you like to join so we can chat instead of misusing github or youtube ) [![Gitter](https://badges.gitter.im/Handleview/community.svg)](https://gitter.im/Handleview/community?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge)
